# Generated by Django 4.2.4 on 2023-09-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_product_date_product_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_des',
            field=models.CharField(max_length=400),
        ),
    ]
