# Generated by Django 4.2.4 on 2023-10-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_product_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('contact', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(default='', max_length=550)),
            ],
        ),
    ]
